name: xride
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  jwt_decode: ^0.3.1
  meta: ^1.15.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
