name: xride
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  google_maps_flutter: ^2.9.0
  jwt_decode: ^0.3.1
  jwt_decoder: ^2.0.1
  location: ^5.0.0
  meta: ^1.15.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/car.png
    - .env
  uses-material-design: true
